[command]
name = "docker"
description = "Manage Docker containers and images."

[[command.subcommands]]
name = "container"
description = "Start or stop an existing container:"

[[command.options]]
short = "-a"
long = "--all"
description = "包含所有（包括隐藏项）"

[[command.options]]
short = ""
long = "--name"
description = "指定名称"

[[command.options]]
short = "-f"
long = "--follow"
description = "强制执行，不提示确认"
